id: jeecgboot-swagger-disclosure

info:
  name: JeecgBoot 后台服务 API 接口文档
  author: zan8in
  severity: high
  verified: true
  description: |-
    fofa: title="Jeecg-Boot"
  tags: jeecg-boot,jeecg,swagger
  created: 2023/07/07

rules:
  r0:
    request:
      method: GET
      path: /jeecg-boot/
    expression: response.status == 200 && response.body.bcontains(b'<title>Swagger-Bootstrap-UI</title>')
  r1:
    request:
      method: GET
      path: /jeecg-boot/swagger-resources
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'"name":') &&
      response.body.bcontains(b'"url":') &&
      response.body.bcontains(b'"swaggerVersion":') &&
      response.body.bcontains(b'"location":')
expression: r0() || r1()
